# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hitagi.ui'
#
# Created: Sat Jan 17 21:44:04 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeView = QtWidgets.QTreeView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeView.setObjectName("treeView")
        self.label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFolder = QtWidgets.QMenu(self.menubar)
        self.menuFolder.setObjectName("menuFolder")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionChangelog = QtWidgets.QAction(MainWindow)
        self.actionChangelog.setObjectName("actionChangelog")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFullscreen = QtWidgets.QAction(MainWindow)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionChange_directory = QtWidgets.QAction(MainWindow)
        self.actionChange_directory.setObjectName("actionChange_directory")
        self.actionInclude_subfolders = QtWidgets.QAction(MainWindow)
        self.actionInclude_subfolders.setCheckable(True)
        self.actionInclude_subfolders.setChecked(True)
        self.actionInclude_subfolders.setObjectName("actionInclude_subfolders")
        self.actionSearch_online = QtWidgets.QAction(MainWindow)
        self.actionSearch_online.setObjectName("actionSearch_online")
        self.actionSet_as_wallpaper = QtWidgets.QAction(MainWindow)
        self.actionSet_as_wallpaper.setObjectName("actionSet_as_wallpaper")
        self.actionCopy_to_clipboard = QtWidgets.QAction(MainWindow)
        self.actionCopy_to_clipboard.setObjectName("actionCopy_to_clipboard")
        self.actionOpen_current_directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_current_directory.setObjectName("actionOpen_current_directory")
        self.menuFile.addAction(self.actionSearch_online)
        self.menuFile.addAction(self.actionSet_as_wallpaper)
        self.menuFile.addAction(self.actionCopy_to_clipboard)
        self.menuFile.addAction(self.actionOpen_current_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOptions)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFolder.addAction(self.actionChange_directory)
        self.menuFolder.addAction(self.actionInclude_subfolders)
        self.menuDisplay.addAction(self.actionFullscreen)
        self.menuHelp.addAction(self.actionChangelog)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFolder.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hitagi Reader 1.0 Alpha"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFolder.setTitle(_translate("MainWindow", "Folder"))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionChangelog.setText(_translate("MainWindow", "Changelog"))
        self.actionAbout.setText(_translate("MainWindow", "About Hitagi"))
        self.actionFullscreen.setText(_translate("MainWindow", "Fullscreen"))
        self.actionChange_directory.setText(_translate("MainWindow", "Change directory"))
        self.actionInclude_subfolders.setText(_translate("MainWindow", "Include subfolders"))
        self.actionSearch_online.setText(_translate("MainWindow", "Search online.."))
        self.actionSet_as_wallpaper.setText(_translate("MainWindow", "Set as wallpaper.."))
        self.actionCopy_to_clipboard.setText(_translate("MainWindow", "Copy to clipboard..."))
        self.actionOpen_current_directory.setText(_translate("MainWindow", "Open current directory..."))

