# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(307, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(307, 400))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setObjectName("button_cancel")
        self.gridLayout.addWidget(self.button_cancel, 1, 2, 1, 1)
        self.button_save = QtWidgets.QPushButton(Dialog)
        self.button_save.setEnabled(False)
        self.button_save.setObjectName("button_save")
        self.gridLayout.addWidget(self.button_save, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_browse_directory = QtWidgets.QPushButton(self.groupBox)
        self.button_browse_directory.setObjectName("button_browse_directory")
        self.gridLayout_5.addWidget(self.button_browse_directory, 1, 1, 1, 1)
        self.input_default_directory = QtWidgets.QLineEdit(self.groupBox)
        self.input_default_directory.setText("")
        self.input_default_directory.setReadOnly(True)
        self.input_default_directory.setObjectName("input_default_directory")
        self.gridLayout_5.addWidget(self.input_default_directory, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.checkbox_check_updates = QtWidgets.QCheckBox(self.groupBox)
        self.checkbox_check_updates.setChecked(True)
        self.checkbox_check_updates.setObjectName("checkbox_check_updates")
        self.gridLayout_5.addWidget(self.checkbox_check_updates, 2, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 3, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.input_background_color = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_background_color.setObjectName("input_background_color")
        self.gridLayout_6.addWidget(self.input_background_color, 1, 0, 1, 1)
        self.button_colorpicker = QtWidgets.QPushButton(self.groupBox_2)
        self.button_colorpicker.setObjectName("button_colorpicker")
        self.gridLayout_6.addWidget(self.button_colorpicker, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.checkbox_hide_menubar = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkbox_hide_menubar.setObjectName("checkbox_hide_menubar")
        self.gridLayout_6.addWidget(self.checkbox_hide_menubar, 3, 0, 1, 2)
        self.checkbox_hide_statusbar = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkbox_hide_statusbar.setObjectName("checkbox_hide_statusbar")
        self.gridLayout_6.addWidget(self.checkbox_hide_statusbar, 4, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_reset = QtWidgets.QPushButton(self.tab_2)
        self.button_reset.setObjectName("button_reset")
        self.gridLayout_2.addWidget(self.button_reset, 5, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setMouseTracking(True)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.input_new_shortcut = QtWidgets.QLineEdit(self.groupBox_4)
        self.input_new_shortcut.setObjectName("input_new_shortcut")
        self.gridLayout_4.addWidget(self.input_new_shortcut, 0, 0, 1, 1)
        self.button_assign = QtWidgets.QPushButton(self.groupBox_4)
        self.button_assign.setObjectName("button_assign")
        self.gridLayout_4.addWidget(self.button_assign, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.input_cur_shortcut = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_cur_shortcut.setReadOnly(True)
        self.input_cur_shortcut.setObjectName("input_cur_shortcut")
        self.gridLayout_3.addWidget(self.input_cur_shortcut, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView_2 = QtWidgets.QListView(self.tab_3)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout.addWidget(self.listView_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.button_cancel.setText(_translate("Dialog", "Cancel"))
        self.button_save.setText(_translate("Dialog", "Save"))
        self.groupBox.setTitle(_translate("Dialog", "Startup"))
        self.button_browse_directory.setText(_translate("Dialog", "Browse"))
        self.label.setText(_translate("Dialog", "Default directory"))
        self.checkbox_check_updates.setText(_translate("Dialog", "Check for updates on startup"))
        self.checkBox.setText(_translate("Dialog", "Start in fullscreen mode"))
        self.groupBox_2.setTitle(_translate("Dialog", "Look and Feel"))
        self.label_2.setText(_translate("Dialog", "Background Color"))
        self.button_colorpicker.setText(_translate("Dialog", "Colorpicker"))
        self.label_3.setText(_translate("Dialog", "Misc"))
        self.checkbox_hide_menubar.setText(_translate("Dialog", "Hide menubar on fullscreen"))
        self.checkbox_hide_statusbar.setText(_translate("Dialog", "Hide statusbar on fullscreen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Layout"))
        self.button_reset.setText(_translate("Dialog", "Reset to defaults"))
        self.groupBox_4.setTitle(_translate("Dialog", "Set new shortcut"))
        self.button_assign.setText(_translate("Dialog", "Assign"))
        self.groupBox_3.setTitle(_translate("Dialog", "Current shortcut for selected option"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Hotkeys"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Language"))

