# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hitagi.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Hitagi(object):
    def setupUi(self, Hitagi):
        Hitagi.setObjectName("Hitagi")
        Hitagi.resize(780, 641)
        Hitagi.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Hitagi.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Hitagi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setInteractive(True)
        self.graphicsView.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        Hitagi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Hitagi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 26))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        self.menuFolder = QtWidgets.QMenu(self.menubar)
        self.menuFolder.setObjectName("menuFolder")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFavorites = QtWidgets.QMenu(self.menubar)
        self.menuFavorites.setObjectName("menuFavorites")
        Hitagi.setMenuBar(self.menubar)
        self.fileWidget = QtWidgets.QDockWidget(Hitagi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileWidget.sizePolicy().hasHeightForWidth())
        self.fileWidget.setSizePolicy(sizePolicy)
        self.fileWidget.setMinimumSize(QtCore.QSize(268, 340))
        self.fileWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.fileWidget.setObjectName("fileWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_2.setSizePolicy(sizePolicy)
        self.dockWidgetContents_2.setMinimumSize(QtCore.QSize(0, 0))
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.treeView = QtWidgets.QTreeView(self.dockWidgetContents_2)
        self.treeView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.treeView.setRootIsDecorated(False)
        self.treeView.setItemsExpandable(False)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 1, 1, 1, 2)
        self.button_favorite = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.button_favorite.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_favorite.setObjectName("button_favorite")
        self.gridLayout.addWidget(self.button_favorite, 0, 2, 1, 1)
        self.button_open_parent = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.button_open_parent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_open_parent.setObjectName("button_open_parent")
        self.gridLayout.addWidget(self.button_open_parent, 0, 1, 1, 1)
        self.fileWidget.setWidget(self.dockWidgetContents_2)
        Hitagi.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.fileWidget)
        self.actionExit = QtWidgets.QAction(Hitagi)
        self.actionExit.setObjectName("actionExit")
        self.actionOptions = QtWidgets.QAction(Hitagi)
        self.actionOptions.setObjectName("actionOptions")
        self.actionChange_directory = QtWidgets.QAction(Hitagi)
        self.actionChange_directory.setObjectName("actionChange_directory")
        self.actionZoom_in = QtWidgets.QAction(Hitagi)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(Hitagi)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionChangelog = QtWidgets.QAction(Hitagi)
        self.actionChangelog.setObjectName("actionChangelog")
        self.actionFullscreen = QtWidgets.QAction(Hitagi)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionAbout = QtWidgets.QAction(Hitagi)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSet_as_wallpaper = QtWidgets.QAction(Hitagi)
        self.actionSet_as_wallpaper.setObjectName("actionSet_as_wallpaper")
        self.actionOpen_current_directory = QtWidgets.QAction(Hitagi)
        self.actionOpen_current_directory.setObjectName("actionOpen_current_directory")
        self.actionCopy_to_clipboard = QtWidgets.QAction(Hitagi)
        self.actionCopy_to_clipboard.setObjectName("actionCopy_to_clipboard")
        self.actionFit_image_width = QtWidgets.QAction(Hitagi)
        self.actionFit_image_width.setObjectName("actionFit_image_width")
        self.actionFit_image_height = QtWidgets.QAction(Hitagi)
        self.actionFit_image_height.setObjectName("actionFit_image_height")
        self.actionOriginal_size = QtWidgets.QAction(Hitagi)
        self.actionOriginal_size.setObjectName("actionOriginal_size")
        self.actionFile_list = QtWidgets.QAction(Hitagi)
        self.actionFile_list.setCheckable(True)
        self.actionFile_list.setChecked(True)
        self.actionFile_list.setObjectName("actionFile_list")
        self.actionOpen_next = QtWidgets.QAction(Hitagi)
        self.actionOpen_next.setObjectName("actionOpen_next")
        self.actionOpen_previous = QtWidgets.QAction(Hitagi)
        self.actionOpen_previous.setObjectName("actionOpen_previous")
        self.actionAdd_to_favorites = QtWidgets.QAction(Hitagi)
        self.actionAdd_to_favorites.setObjectName("actionAdd_to_favorites")
        self.actionRemove_from_favorites = QtWidgets.QAction(Hitagi)
        self.actionRemove_from_favorites.setObjectName("actionRemove_from_favorites")
        self.menuExit.addAction(self.actionSet_as_wallpaper)
        self.menuExit.addAction(self.actionCopy_to_clipboard)
        self.menuExit.addAction(self.actionOpen_current_directory)
        self.menuExit.addSeparator()
        self.menuExit.addAction(self.actionOptions)
        self.menuExit.addSeparator()
        self.menuExit.addAction(self.actionExit)
        self.menuFolder.addAction(self.actionOpen_next)
        self.menuFolder.addAction(self.actionOpen_previous)
        self.menuFolder.addSeparator()
        self.menuFolder.addAction(self.actionChange_directory)
        self.menuFolder.addSeparator()
        self.menuFolder.addAction(self.actionAdd_to_favorites)
        self.menuFolder.addAction(self.actionRemove_from_favorites)
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menuView.addAction(self.actionOriginal_size)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFit_image_width)
        self.menuView.addAction(self.actionFit_image_height)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFile_list)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFullscreen)
        self.menuHelp.addAction(self.actionChangelog)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFavorites.addSeparator()
        self.menubar.addAction(self.menuExit.menuAction())
        self.menubar.addAction(self.menuFolder.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuFavorites.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Hitagi)
        QtCore.QMetaObject.connectSlotsByName(Hitagi)

    def retranslateUi(self, Hitagi):
        _translate = QtCore.QCoreApplication.translate
        Hitagi.setWindowTitle(_translate("Hitagi", "Hitagi Reader"))
        self.menuExit.setTitle(_translate("Hitagi", "File"))
        self.menuFolder.setTitle(_translate("Hitagi", "Folder"))
        self.menuView.setTitle(_translate("Hitagi", "View"))
        self.menuHelp.setTitle(_translate("Hitagi", "Help"))
        self.menuFavorites.setTitle(_translate("Hitagi", "Favorites"))
        self.fileWidget.setWindowTitle(_translate("Hitagi", "Files"))
        self.button_favorite.setText(_translate("Hitagi", "Favorite"))
        self.button_open_parent.setText(_translate("Hitagi", "Open parent"))
        self.actionExit.setText(_translate("Hitagi", "Exit"))
        self.actionOptions.setText(_translate("Hitagi", "Options"))
        self.actionChange_directory.setText(_translate("Hitagi", "Change directory"))
        self.actionZoom_in.setText(_translate("Hitagi", "Zoom in"))
        self.actionZoom_out.setText(_translate("Hitagi", "Zoom out"))
        self.actionChangelog.setText(_translate("Hitagi", "Changelog"))
        self.actionFullscreen.setText(_translate("Hitagi", "Fullscreen"))
        self.actionAbout.setText(_translate("Hitagi", "About Hitagi"))
        self.actionSet_as_wallpaper.setText(_translate("Hitagi", "Set as wallpaper..."))
        self.actionOpen_current_directory.setText(_translate("Hitagi", "Open current directory..."))
        self.actionCopy_to_clipboard.setText(_translate("Hitagi", "Copy to clipboard..."))
        self.actionFit_image_width.setText(_translate("Hitagi", "Fit to width"))
        self.actionFit_image_height.setText(_translate("Hitagi", "Fit to height"))
        self.actionOriginal_size.setText(_translate("Hitagi", "Zoom 100%"))
        self.actionFile_list.setText(_translate("Hitagi", "File list"))
        self.actionOpen_next.setText(_translate("Hitagi", "Open next"))
        self.actionOpen_previous.setText(_translate("Hitagi", "Open previous"))
        self.actionAdd_to_favorites.setText(_translate("Hitagi", "Add to favorites"))
        self.actionRemove_from_favorites.setText(_translate("Hitagi", "Remove from favorites"))

from resources import hitagi_rc
