# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(307, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(307, 400))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 1, 2, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_browse_directory = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_browse_directory.setObjectName("pushButton_browse_directory")
        self.gridLayout_5.addWidget(self.pushButton_browse_directory, 1, 1, 1, 1)
        self.lineEdit_default_directory = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_default_directory.setText("")
        self.lineEdit_default_directory.setReadOnly(True)
        self.lineEdit_default_directory.setObjectName("lineEdit_default_directory")
        self.gridLayout_5.addWidget(self.lineEdit_default_directory, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.checkBox_check_updates = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_check_updates.setChecked(True)
        self.checkBox_check_updates.setObjectName("checkBox_check_updates")
        self.gridLayout_5.addWidget(self.checkBox_check_updates, 2, 0, 1, 2)
        self.checkBox_fullscreen_mode = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_fullscreen_mode.setObjectName("checkBox_fullscreen_mode")
        self.gridLayout_5.addWidget(self.checkBox_fullscreen_mode, 3, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_hide_menubar = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_hide_menubar.setObjectName("checkBox_hide_menubar")
        self.gridLayout_6.addWidget(self.checkBox_hide_menubar, 4, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_background_color = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_background_color.setObjectName("lineEdit_background_color")
        self.gridLayout_6.addWidget(self.lineEdit_background_color, 1, 0, 1, 1)
        self.pushButton_colorpicker = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_colorpicker.setObjectName("pushButton_colorpicker")
        self.gridLayout_6.addWidget(self.pushButton_colorpicker, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_default_viewport = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_default_viewport.setObjectName("comboBox_default_viewport")
        self.comboBox_default_viewport.addItem("")
        self.comboBox_default_viewport.addItem("")
        self.comboBox_default_viewport.addItem("")
        self.comboBox_default_viewport.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_default_viewport)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_reset = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout_2.addWidget(self.pushButton_reset, 5, 0, 1, 1)
        self.listWidget_hotkey = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_hotkey.setMouseTracking(True)
        self.listWidget_hotkey.setObjectName("listWidget_hotkey")
        self.gridLayout_2.addWidget(self.listWidget_hotkey, 0, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_new_shortcut = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_new_shortcut.setObjectName("lineEdit_new_shortcut")
        self.gridLayout_4.addWidget(self.lineEdit_new_shortcut, 0, 0, 1, 1)
        self.pushButton_assign_hotkey = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_assign_hotkey.setObjectName("pushButton_assign_hotkey")
        self.gridLayout_4.addWidget(self.pushButton_assign_hotkey, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_current_shortcut = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_current_shortcut.setReadOnly(True)
        self.lineEdit_current_shortcut.setObjectName("lineEdit_current_shortcut")
        self.gridLayout_3.addWidget(self.lineEdit_current_shortcut, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_locale = QtWidgets.QListWidget(self.tab_3)
        self.listWidget_locale.setObjectName("listWidget_locale")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/en_US.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget_locale.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/de_DE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget_locale.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/ja_JP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget_locale.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/vi_VN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget_locale.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_locale)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
        self.groupBox.setTitle(_translate("Dialog", "Startup"))
        self.pushButton_browse_directory.setText(_translate("Dialog", "Browse"))
        self.label.setText(_translate("Dialog", "Default directory"))
        self.checkBox_check_updates.setText(_translate("Dialog", "Check for updates on startup"))
        self.checkBox_fullscreen_mode.setText(_translate("Dialog", "Start in fullscreen mode"))
        self.groupBox_2.setTitle(_translate("Dialog", "Look and Feel"))
        self.checkBox_hide_menubar.setText(_translate("Dialog", "Hide menubar on fullscreen"))
        self.label_2.setText(_translate("Dialog", "Background Color"))
        self.pushButton_colorpicker.setText(_translate("Dialog", "Colorpicker"))
        self.label_3.setText(_translate("Dialog", "Misc"))
        self.groupBox_3.setTitle(_translate("Dialog", "Default viewport behaviour"))
        self.comboBox_default_viewport.setItemText(0, _translate("Dialog", "Ratio scaling"))
        self.comboBox_default_viewport.setItemText(1, _translate("Dialog", "Fit to width"))
        self.comboBox_default_viewport.setItemText(2, _translate("Dialog", "Fit to height"))
        self.comboBox_default_viewport.setItemText(3, _translate("Dialog", "Original size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Layout"))
        self.pushButton_reset.setText(_translate("Dialog", "Reset to defaults"))
        self.groupBox_5.setTitle(_translate("Dialog", "Set new shortcut"))
        self.pushButton_assign_hotkey.setText(_translate("Dialog", "Assign"))
        self.groupBox_4.setTitle(_translate("Dialog", "Current shortcut for selected option"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Hotkeys"))
        __sortingEnabled = self.listWidget_locale.isSortingEnabled()
        self.listWidget_locale.setSortingEnabled(False)
        item = self.listWidget_locale.item(0)
        item.setText(_translate("Dialog", "English"))
        item = self.listWidget_locale.item(1)
        item.setText(_translate("Dialog", "Deutsch (German)"))
        item = self.listWidget_locale.item(2)
        item.setText(_translate("Dialog", "日本語 (Japanese)"))
        item = self.listWidget_locale.item(3)
        item.setText(_translate("Dialog", "Tiếng Việt (Vietnamese)"))
        self.listWidget_locale.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Language"))

from resources import hitagi_rc
