# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hitagi.ui'
#
# Created: Mon Oct 13 16:43:27 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(809, 604)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mainwindow.sizePolicy().hasHeightForWidth())
        Mainwindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icon/64x64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mainwindow.setWindowIcon(icon)
        Mainwindow.setAutoFillBackground(False)
        Mainwindow.setStyleSheet("")
        Mainwindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        Mainwindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(Mainwindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.treeView = QtGui.QTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeView.setObjectName("treeView")
        self.imageContainer = QtGui.QLabel(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageContainer.sizePolicy().hasHeightForWidth())
        self.imageContainer.setSizePolicy(sizePolicy)
        self.imageContainer.setStyleSheet("")
        self.imageContainer.setText("")
        self.imageContainer.setScaledContents(False)
        self.imageContainer.setAlignment(QtCore.Qt.AlignCenter)
        self.imageContainer.setWordWrap(False)
        self.imageContainer.setMargin(0)
        self.imageContainer.setObjectName("imageContainer")
        self.verticalLayout.addWidget(self.splitter)
        Mainwindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(Mainwindow)
        self.statusBar.setObjectName("statusBar")
        Mainwindow.setStatusBar(self.statusBar)
        self.menubar = QtGui.QMenuBar(Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        Mainwindow.setMenuBar(self.menubar)
        self.actionSubfolder = QtGui.QAction(Mainwindow)
        self.actionSubfolder.setCheckable(True)
        self.actionSubfolder.setChecked(True)
        self.actionSubfolder.setObjectName("actionSubfolder")
        self.actionChange_directory = QtGui.QAction(Mainwindow)
        self.actionChange_directory.setObjectName("actionChange_directory")
        self.actionExit = QtGui.QAction(Mainwindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDialog_Changelog = QtGui.QAction(Mainwindow)
        self.actionDialog_Changelog.setObjectName("actionDialog_Changelog")
        self.actionDialog_About = QtGui.QAction(Mainwindow)
        self.actionDialog_About.setObjectName("actionDialog_About")
        self.actionFullscreen = QtGui.QAction(Mainwindow)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionOptions = QtGui.QAction(Mainwindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionCopy = QtGui.QAction(Mainwindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionDelete = QtGui.QAction(Mainwindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSet_as_wallpaper = QtGui.QAction(Mainwindow)
        self.actionSet_as_wallpaper.setObjectName("actionSet_as_wallpaper")
        self.actionSearch_online = QtGui.QAction(Mainwindow)
        self.actionSearch_online.setObjectName("actionSearch_online")
        self.actionOpen_folder = QtGui.QAction(Mainwindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionOpen_current_directory = QtGui.QAction(Mainwindow)
        self.actionOpen_current_directory.setObjectName("actionOpen_current_directory")
        self.menuFile.addAction(self.actionSearch_online)
        self.menuFile.addAction(self.actionSet_as_wallpaper)
        self.menuFile.addAction(self.actionCopy)
        self.menuFile.addAction(self.actionOpen_current_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOptions)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOption.addAction(self.actionChange_directory)
        self.menuOption.addAction(self.actionSubfolder)
        self.menuAbout.addAction(self.actionDialog_Changelog)
        self.menuAbout.addAction(self.actionDialog_About)
        self.menuDisplay.addAction(self.actionFullscreen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        Mainwindow.setWindowTitle(QtGui.QApplication.translate("Mainwindow", "Hitagi Reader", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Mainwindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOption.setTitle(QtGui.QApplication.translate("Mainwindow", "Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("Mainwindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDisplay.setTitle(QtGui.QApplication.translate("Mainwindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSubfolder.setText(QtGui.QApplication.translate("Mainwindow", "Include subfolders..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_directory.setText(QtGui.QApplication.translate("Mainwindow", "Change directory..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_directory.setShortcut(QtGui.QApplication.translate("Mainwindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("Mainwindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("Mainwindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDialog_Changelog.setText(QtGui.QApplication.translate("Mainwindow", "Changelog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDialog_About.setText(QtGui.QApplication.translate("Mainwindow", "About Hitagi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setText(QtGui.QApplication.translate("Mainwindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setShortcut(QtGui.QApplication.translate("Mainwindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("Mainwindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("Mainwindow", "Copy to clipboard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("Mainwindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_as_wallpaper.setText(QtGui.QApplication.translate("Mainwindow", "Set as wallpaper..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch_online.setText(QtGui.QApplication.translate("Mainwindow", "Search online..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_folder.setText(QtGui.QApplication.translate("Mainwindow", "Open current folder..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_current_directory.setText(QtGui.QApplication.translate("Mainwindow", "Open current directory..", None, QtGui.QApplication.UnicodeUTF8))

