# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hitagi.ui'
#
# Created: Mon Sep 22 22:11:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(809, 604)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mainwindow.sizePolicy().hasHeightForWidth())
        Mainwindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        Mainwindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mainwindow.setWindowIcon(icon)
        Mainwindow.setAutoFillBackground(False)
        Mainwindow.setStyleSheet("")
        Mainwindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        Mainwindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(Mainwindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logoContainer = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoContainer.sizePolicy().hasHeightForWidth())
        self.logoContainer.setSizePolicy(sizePolicy)
        self.logoContainer.setStyleSheet("background-color: #E5E3E3;padding:0px 5px;")
        self.logoContainer.setObjectName("logoContainer")
        self.horizontalLayout_2.addWidget(self.logoContainer)
        self.headerContainer = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerContainer.sizePolicy().hasHeightForWidth())
        self.headerContainer.setSizePolicy(sizePolicy)
        self.headerContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.headerContainer.setStyleSheet("background-color: #E5E3E3;padding:15px 5px;font-size:20px;color:#333;")
        self.headerContainer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.headerContainer.setObjectName("headerContainer")
        self.horizontalLayout_2.addWidget(self.headerContainer)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.imageContainer = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageContainer.sizePolicy().hasHeightForWidth())
        self.imageContainer.setSizePolicy(sizePolicy)
        self.imageContainer.setStyleSheet("")
        self.imageContainer.setText("")
        self.imageContainer.setScaledContents(False)
        self.imageContainer.setAlignment(QtCore.Qt.AlignCenter)
        self.imageContainer.setWordWrap(False)
        self.imageContainer.setMargin(0)
        self.imageContainer.setObjectName("imageContainer")
        self.verticalLayout.addWidget(self.imageContainer)
        Mainwindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(Mainwindow)
        self.statusBar.setObjectName("statusBar")
        Mainwindow.setStatusBar(self.statusBar)
        self.menubar = QtGui.QMenuBar(Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        Mainwindow.setMenuBar(self.menubar)
        self.actionSubfolder = QtGui.QAction(Mainwindow)
        self.actionSubfolder.setCheckable(True)
        self.actionSubfolder.setObjectName("actionSubfolder")
        self.actionOpenDirectory = QtGui.QAction(Mainwindow)
        self.actionOpenDirectory.setObjectName("actionOpenDirectory")
        self.actionExit = QtGui.QAction(Mainwindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelpChangelog = QtGui.QAction(Mainwindow)
        self.actionHelpChangelog.setObjectName("actionHelpChangelog")
        self.actionHelpHitagi = QtGui.QAction(Mainwindow)
        self.actionHelpHitagi.setObjectName("actionHelpHitagi")
        self.actionFullscreen = QtGui.QAction(Mainwindow)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionHelpPySide = QtGui.QAction(Mainwindow)
        self.actionHelpPySide.setObjectName("actionHelpPySide")
        self.menuFile.addAction(self.actionOpenDirectory)
        self.menuFile.addAction(self.actionExit)
        self.menuOption.addAction(self.actionSubfolder)
        self.menuOption.addAction(self.actionFullscreen)
        self.menuAbout.addAction(self.actionHelpChangelog)
        self.menuAbout.addAction(self.actionHelpHitagi)
        self.menuAbout.addAction(self.actionHelpPySide)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        Mainwindow.setWindowTitle(QtGui.QApplication.translate("Mainwindow", "Hitagi", None, QtGui.QApplication.UnicodeUTF8))
        self.logoContainer.setText(QtGui.QApplication.translate("Mainwindow", "Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.headerContainer.setText(QtGui.QApplication.translate("Mainwindow", "Reader", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Mainwindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOption.setTitle(QtGui.QApplication.translate("Mainwindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("Mainwindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSubfolder.setText(QtGui.QApplication.translate("Mainwindow", "Include subfolders", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDirectory.setText(QtGui.QApplication.translate("Mainwindow", "Open directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDirectory.setShortcut(QtGui.QApplication.translate("Mainwindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("Mainwindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("Mainwindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpChangelog.setText(QtGui.QApplication.translate("Mainwindow", "Changelog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpHitagi.setText(QtGui.QApplication.translate("Mainwindow", "About Hitagi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setText(QtGui.QApplication.translate("Mainwindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setShortcut(QtGui.QApplication.translate("Mainwindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpPySide.setText(QtGui.QApplication.translate("Mainwindow", "About PySide", None, QtGui.QApplication.UnicodeUTF8))

